### ISSUE TITLE
Universal Search

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#1]
A fulltext search that returns results from all (or a selected subset) of providers.

**Comment by oxan** [comment]
Implement using a new method in ILibrary returning a List of WebSearchResult with id / type / title.

**Comment by DieBagger** [comment]
A few things that should be added to search:
- results should be sorted from best match to worst match and not grouped by provider
- client should be able to get ranged search results -> Search(String text, int start, int end), or at least be able to set a limit on the returned items (maxResults)
- websearchresult needs a field for "provider" so we know where the result came fom

**Comment by oxan** [comment]
That's all implemented now with 4dc7116, 77cbfe7 and 390e097. Subsequent improvements are now tracked in #22.
