### ISSUE TITLE
Add functions to delete recordings

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#100]
Add functions to delete recordings

Does the TV server offer support for this?

**Comment by tlindener** [comment]
As far as i know recording is nothing supported by any tvserver library. It's solely based on filesystem support means:
We have to access the files directly...(and we have to remember to delete both recording and meta data)

**Comment by oxan** [comment]
Hmm yeah. If the TV server doesn't do it then i don't think we should implement it.

**Comment by augustinmarx** [comment]
TvControl.DeleteRecording (see file TVController.cs) ...
