### ISSUE TITLE
Use ffmpeg 0.10

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#101]
Let's start tracking a stable branch of ffmpeg instead of git master. Only problem is that there don't seem to be Windows builds of?

**Comment by DieBagger** [comment]
ffmpeg 0.9.1 is out btw: http://www.ffmpeg.org/download.html#release_0.9

**Comment by offbyoneBB** [comment]
Should be one of those: ?
http://ffmpeg.zeranoe.com/builds/win32/static/

**Comment by oxan** [comment]
No, that are all builds of the master (unstable) branch. He doesn't provide Windows builds of the stable releases unfortunately.

**Comment by oxan** [comment]
0.10 is already out too now... If they keep going this quick with updates using a stable branch doesn't help...

**Comment by tlindener** [comment]
Do you think it would be possible to implement Intels QuickSync Transcoding Feature? (Existing since Sandy Bridge)

http://software.intel.com/en-us/articles/vcsource-samples-video-transcoder-using-media-sdk/

**Comment by DieBagger** [comment]
Hm just had a short look at it:
- There's a c++ sdk (plus example source available)
- The sdk itself has no open source license (not sure how this would affect us)
- It's limited to input and output being h264/mpeg-2 or mpeg... 

Aside from someone having to write a c++ wrapper for this, we'd also need code changes to support this (can only be used when cpu/file format support it). 

It would be great to have (same for gpu decoding), but I think this should be implmenented in ffmpeg/vlc and not on our side.

**Comment by oxan** [comment]
Given that;
- Intel doesn't have publically available documentation on the interface to the hardware (added instructions);
- The only way to use it is their Media SDK, which is closed-source and only available for Windows;
- Intel doesn't have any intention to actually release the needed documentation; 
- The opinion of the ffmpeg/vlc/x264 developers is (understandably) pretty much "f**\* Intel"
  I don't see _any_ chance at all for this to get implemented in an open source encoder the coming years. 

Take that; add
- that I don't want to bother with actually implementing codecs myself;
- that my opinion on this is about the same as the ffmpeg/vlc/x264 developers;
- that I don't have nor intend to buy a Sandy Bridge CPU; 
  which makes the chances of it getting implemented pretty much zero. But of course, if someone else creates a sane patch, I'm happy to consider it. 

@DieBagger: we already have GPU decoding for VLC, but the decoding is just around ~10% of the used CPU power so no-one really notices it.

**Comment by lyfesaver** [comment]
As an owner of a 2nd Gen i3 and i5, it saddens me that Quick Sync is ootq. =( the tanscoding power of this feature is truly awesome =)

**Comment by bodiroga** [comment]
And what about openCL support? New AMDs Trinity CPU/GPUs are AWESOME accelerating openCL with their GPU and their power consumption is very low, so they seems to be great home server CPUs ;-) (Adobe, WinZip, Gimp, PowerDVD,... are going to support openCL in their new products, so its future looks promising)

**Comment by oxan** [comment]
Yeah, the only relevant thing still is whether ffmpeg/vlc implements it or someone who's willing to do the work steps up. Anyway, this is becoming more and more offtopic here.

**Comment by oxan** [comment]
This has been merged now.
