### ISSUE TITLE
Fix streaming to outside the local LAN

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#110]
We really have to proxy the stream in WebMP sometime as we can't assume everyone has access to the service.

**Comment by oxan** [comment]
This is actually implemented for master in 030fea6, still need to port that to release-0.4.

**Comment by oxan** [comment]
Implemented in 646aa66b4e413c234abb309c79239495195afbcd, but needs some testing.

**Comment by lyfesaver** [comment]
I would test, but I have no idea how to use Git

**Comment by oxan** [comment]
I'll prepare an installer for you somewhere this week :)

**Comment by oxan** [comment]
Confirmed.
