### ISSUE TITLE
FR: Add mvC to MPE accepted plugins

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#111]
Music Videos please sir!!!!!

MvC is the premier music video plugin for MP at the time and it has become very popular ans stable. Could you please add it to MPE?

It uses MovPic and TVS code so i am hoping that it wont be too much trouble to add.

Would be good for WebMP and aMPdroid

Below is a quick conversation with Trevor (creator of mvCentral)

[16:34] Lyfesaver> ya trevor i am putting in a request to put mvC in MPE too so aMPdroid and WebMP will play them =)
[16:35] Lyfesaver> should not be too hard seeing as how he has TVS and u used TVS core code
[16:35] trevor|home> sounds good - MvC uses some of MovPics and TvS
[16:35] trevor|home> but if he needs any help give me a shout
[16:36] Lyfesaver> i thot movpic was just the importer side
[16:36] trevor|home> true
[16:36] Lyfesaver> kk
[16:36] Lyfesaver> he should not have anything to do with that then
[16:37] trevor|home> well...the DB access is all MovPics though the actual player is TvS based...
[16:37] Lyfesaver> ahhhh kk gotcha
[16:37] trevor|home> if he has got MovPics already this is just another DB to look at

**Comment by oxan** [comment]
If it really uses the same database structure as mopi i can easily include it. Can you verify that or send me a database example?

**Comment by lyfesaver** [comment]
I can send it or u can RDP and copy it. It is in with the other databases.

**Comment by oxan** [comment]
Hmm, the DB layout is like mopi but it's not 100% mopi, which complicates things...

**Comment by lyfesaver** [comment]
Hmmmmm, do you need any info from Trevor?

**Comment by oxan** [comment]
Not yet...

**Comment by tlindener** [comment]
Wasn't the intention to add the plugin architecture that we aren't the only ones to new sources any longer?

**Comment by oxan** [comment]
So?

**Comment by tlindener** [comment]
The question is what is it we should currently focus on....

**Comment by oxan** [comment]
Yeah I agree. But if the database would've been the same as mopi it would be only a few lines of code. 

(I didn't assign a milestone yet, so it's not on my short-term todo ;))

**Comment by lyfesaver** [comment]
"it's not on my short-term todo"

crap =( I had been sitting on my hands hoping it was easy enough to put on your short-term todo list =(

Any ideas on how I can get my music videos into MPE otherwise? It saddens me that I have this nice tablet to listen to MP3s on =( Nice beautiful capacitive touch screen to listen to the raido =)

**Comment by oxan** [comment]
Well, it's a bit annoying that the database isn't exactly equal to movpics. With the current development speed I'll probably get to it in a few weeks anyway. But does aMPdroid even have music streaming support? That's a requirement to get it on your tablet too.

**Comment by lyfesaver** [comment]
Sorry I never answered you, but yes, aMPdroid allows for music streaming.

**Comment by DieBagger** [comment]
no it doesn't support streaming music yet... And anyhow we're talking about music VIDEOS, aren't we?

**Comment by oxan** [comment]
Didn't we want to implement it as a music plugin? 

```
03-01-2012 21:11:51 > oxan: hmm.. wondering a bit whether i should implement mvCentral as a music or movie plugin
03-01-2012 21:12:24 > oxan: music seems to make more sense but we don't have video support for music yet
03-01-2012 21:14:19 < DieBagger: i would also say music
```

**Comment by DieBagger** [comment]
yes but it would still serve videos, not music streams...

**Comment by lyfesaver** [comment]
DieBagger, the way Oxan described it was that MPE does allow direct acces to MP databases, it takes the databases and rebuilds it in away (either music or video) that aMPdroid and WebMP can read it. So one has to be picked and used. I was under the impression that aMPdroid did stream music as it has a music button and I thot I had tested it before.

**Comment by lyfesaver** [comment]
sry i clikced the close & comment button, but i reopened it

**Comment by oxan** [comment]
Yeah the placement of that button sucks :/

anyway, let me get back to this on IRC in a few days. Have to try the plugin to make a good judgement. Btw, we can enable video streaming for a music plugin.
