### ISSUE TITLE
WebMP: Restrict adult content visibility

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#112]
I would like it if WebMP could have some sort of function to hide/show adult content.

**Comment by oxan** [comment]
Would need some way to indicate adult content... My personal opinion on this is more or less "don't add it if you don't want to see it". Maybe make some general "rating" system so that we can also restrict PG-13 content etc. 

anyway, i think there are more important things right now.

**Comment by lyfesaver** [comment]
Well, once u have Genres/Categories working ti will be a breeze =) Just deny the access of the "Adult" genre

**Comment by oxan** [comment]
I like to do things properly instead of hacking up something (i.e. no hardcoded category or genre names). There's already way too much unmaintainable code out there in the MP ecosystem.

**Comment by lyfesaver** [comment]
I dont understand... are you saying you dont want to implement Genres? That is the main category I use to browse movies.

**Comment by oxan** [comment]
No, that I don't want to implement restrictions for the adult genre. Restricting certain content for people should be done in a proper way (permission system), not just restricting access to a genre on condition x.

Genres actually are already implemented, but not in WebMP yet.

**Comment by lyfesaver** [comment]
Ya i figured they were as aMPdroid is using them.

**Comment by lyfesaver** [comment]
This can be done at the client level very easily and I think that this issue "COULD" be closed unless u wish to make this a server side argument. That being said as long as the services offers a way to denote this in webmoviesbasic (currently by genres) client side might be the best way to control this. All adult content MUST be in the Adult genre. Or with the edited WebMP which used detailed vs basic for listing, the content rating is another back up system for it as well.
