### ISSUE TITLE
FR: Categories for Movies (and maybe TVS) in WebMP

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#113]
As it stand when you go to browse the list of movies in WebMP you get them all in one list. This is workable, but if you get some extra time and an itch to do it, I would like to have some sort of sorting for the movies. Genres, years and actors would most likely be best native categories, but the optimal way would be to just use the categories that the user has already assigned in the Movies database.

**Comment by oxan** [comment]
Duplicate of #54.
