### ISSUE TITLE
FR: Activate Media Importing

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#115]
Let me give u a brief example of my setup so you can better understand why this is important.

Everyone in our house their own personal laptop for use and we have 1 desktop that acts a server for all kinds of things, mainly MediaPortal. It never actually has MP running though, just the server software, so it does not have TVS or MovPic running to get recent additions. 

Is it possible to have MPE take control of this? And if so to have it do it on a daily basis and perhaps a as needed basis via WebMP?

**Comment by oxan** [comment]
This is possible but not really sure if we want it: it means that we've to actually link against mopi and mptvseries, and I'm not sure they have a (stable) API. Also causes problems with updating mopi and mptvseries independent from mpext.

**Comment by tlindener** [comment]
I think it would be easier to install MP on the server and ask for the ability to run the importer without starting MP(and may be Windows task scheduler based)

It would be a huge amount of work to make this happen and as oxan already said could cause many side effects(although i had also thought about it)

**Comment by oxan** [comment]
```
[20:43:09] <Lyfesaver> btw, Oxan... there is another issue u can close
[20:43:19] <oxan> which one?
[20:43:33] <Lyfesaver> the one i opened, asking MPE to activate Importing
[20:43:37] <Lyfesaver> its not gunna happen
[20:43:39] <Lyfesaver> =)
```

Way too complex to handle with all the different plugins.

**Comment by lyfesaver** [comment]
Not only would it be hard to handle each plugin... but impossible atm as none of the plugins have a command line "call" for running a background import =( 

Maybe if in the future MovPic, MP-TVS, mvC or MePoMusic allow a simple call like 'config.exe /runimport' then it would not be hard to assign a link to this feature.
