### ISSUE TITLE
FR: incl WebMP streaming in the "Streaming List" in MPEC

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#116]
It would be nice if the streaming list in the MPE configuration would icl anyone streaming via WebMP.

**Comment by oxan** [comment]
It does. Should I see this as "it's-not-working"?

**Comment by lyfesaver** [comment]
Well, I Looked and did not see it, let me check again

**Comment by lyfesaver** [comment]
Cant verify atm as it seems streaming is broken again for me.

**Comment by lyfesaver** [comment]
Okay, I restarted my server PC and WebMP is working again and yes WebMP activity does show in the streaming box of MPEC. 

Guess restarting server PC fixed more than one thing for me.

Closing issue.
