### ISSUE TITLE
GetMediaInfo gets wrong Movie info

### ISSUE THREAD

**Issue by PatSer81** [MPExtended/MPExtended#117]
When requesting media info with GetMediaInfo?type=0&provider=3&itemId=[moving pictures id] MPextended returns info from the wrong file.
For example if I request with itemId=209, I get the info belonging to MoPi id nr. 216
The error does not happen with every ID (I think, the only way I can see the error is when there is a .srt file present)

**Comment by oxan** [comment]
That would be very, very strange :/

**Comment by PatSer81** [comment]
I've tested it with several movies.
The only way I can see that the info is wrong is when the movie has external subs and mediainfo shows the .srt file.
For instance when I request id: 209 "The Wolfman", I get the info from id:216 "Transporter 3" (because mediainfo says that the external sub file is "Transporter 3.srt")
I don't have srt files with all of my movies, so I can't check them all.
Also I notice the error when comparing width/height info from MPext with the MoPi DB.

**Comment by oxan** [comment]
That means that the source path for which we load media info is wrong. Can you verify that the correct path is in the GetAllMoviesBasic output?

**Comment by PatSer81** [comment]
Found the problem (i think)! The ID from MoPi isn't always the same as the local media ID.
MoPi uses a crosslist table: local_media__movie_info
Am I right if I say that when one requests mediainfo the given id is looked up in the local media table and not the movie info table?
