### ISSUE TITLE
Redesign WebMP

### ISSUE THREAD

**Issue by tlindener** [MPExtended/MPExtended#130]
Since there seems to be some undicussed things about how WebMP should look in the future, i would like to do this here to allow some async communication.

Since the latest draft based on a more graphical layout isn't as promising as i had hoped, i looked for existing UI which offer similar actions like we want and found that the Google Music layout seems to be a good approach with a few additions.

http://beatmasters-winlite-blog.de/wp-content/uploads//2011/08/Google_Music_Desktop_Player-1.jpg

Additions we need would be to add the existing horizontal navigation to adress not only music but all the other media types too. 
As a result we can use the left navigation as some kind of sub navigation for things like sorting/ordering or specialized views.

E.g. we could add only one TV Tab at the top and move the other tabs to the sub navigation.

**Comment by oxan** [comment]
Aredon's layout has been merged now, and work on this (afaik) abandoned.
