### ISSUE TITLE
Notifications interface for "Push Notifications"

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#132]
Implement an interface for sending notifications to clients when they are not connected. This is possible on many platforms:
- Android: C2DM
- iOS: Push Notifications
- Windows Mobile: MPN
- Desktop Clients: Running WCF webservice on client

Since the client wouldn't need to be connected to a service to receive these notifications it would help save battery life on the remotes.

Some usage scenarios for this would be:
- Sending the server configuration to clients for easy setup
- Notification when MediaPortal is started/closed
- Notification when server is started
- Notification when a recording starts
- Notification on conflicting schedules
- Notification when tvservice or mediaportal crashes
- Pinging the client (device starts emitting a signal tone)

**Comment by Thorsten1982** [comment]
I don't know if it would be possible, but I think this should work in the other direction, too. 

So if you get a call on your mobilephone you will see a message in Mediaportal and Playback will pause.

**Comment by DieBagger** [comment]
That's something completely different, you already have a listener (wifiremote) on MediaPortal. So what you're describing is in fact already possible.

**Comment by Thorsten1982** [comment]
Okay can this implement in AmpDroid ? Or what do you thing is the best way. Now I use Eventghost on Android and the PC and I think it the Messenger Plugin for Mediaportal is needed. With this app I can pause Mediaportal and send a message on Mediaportal. But there are so many Apps needed, so I hope it can implement in one of these Apps like Ampdroid.

**Comment by oxan** [comment]
Phone -> MP notifications have nothing to do with MPExtended though.

**Comment by Thorsten1982** [comment]
Okay, you're right it has nothing to do with MPExtended, but maybee a litte with Wifiremote and AmPdroid. So I thing this is the right Place, to discuss this

**Comment by oxan** [comment]
No, it isn't. This is about a feature request for MPExtended, not a feature remotely related to this in another product.

**Comment by bodiroga** [comment]
Hi guys! Apart from the Phone -> MP and MP -> Phone discussion, which is the actual state of this feature request? Is there any plan to include it? I'm not asking "when", just if Oxan has considered it ;-) It would be so cool to include this is aMPdroid...

**Comment by oxan** [comment]
Still just an idea...

**Comment by oxan** [comment]
Maybe we could use this? https://pushover.net/ It looks pretty cool :)

**Comment by bodiroga** [comment]
www.notifymyandroid.com looks great also, although it is just for Android ;)

**Comment by Shukuyen** [comment]
The most popular such services for iOS are 
- http://prowlapp.com/
- http://boxcar.io/

I personally don't think most of those push notifications fit in the scope of mp-extended but should have their own MediaPortal plugin :) Also a good use case is still missing, imho

**Comment by oxan** [comment]
If we implement this, it'll certainly be extensible: each client can drop a DLL in a directory to use a custom "delivery service". I'm not sure whether it should be a MP or MPExtended plugin. MPExtended is certainly easier to implement for me :). If we implement it in MPExtended we could also create a MP plugin that sends messages through MPExtended.

But yeah, I haven't found a really good use case yet.. Just posted the link as I stumpled upon it and wanted to preserve it ;)

**Comment by DieBagger** [comment]
@oxan didn't I list a few use-cases in my original post? ;) Personally I don't really like these push services since they just add an extra layer to an already working system (and in some cases even require additional software on the device).

Fyi, google recently changed their push notification service from C2DM to GCM (google cloud messaging) and officially lifted the "beta" status.

I also talked to high and he said that it wouldn't be a problem to run a server script on of the MediaPortal servers where we could store all "registered" clients and which would send the push notifications to clients. It would also be possible to run this without a dedicated "push" server, but then each user would have to sign up for an api key. 

I would imagine a push setup like this:
- User pressed "Add client via code" and a client and gets a random number
- The client sends this number (and type of device, iOS/Android/WP) to the MediaPortal server which stores it along with the device id
- In the MpExtended configuration, the user enters the code and presses "Send configuration to device"
- MpExtended sends a request with the code + config to MP server (should be encrypted/https)
- MP server looks up the device linked to the code and sends the notification via push notfication
- Voila, Client has the complete server config

**Comment by oxan** [comment]
@DieBagger yeah, but I don't want notifications for any of those things :P Though I can imagine people will want them.

Anyway, I just listed Pushover as I came across it, I really don't have a clue about how push messaging on Android works.

Running a push server isn't a problem I think. Your setup sounds good ;)
