### ISSUE TITLE
Service fails to start because of NLog error

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#137]
http://forum.team-mediaportal.com/mpextended-555/updated-30-dec-mpextended-service-0-4-1-a-103873/index6.html#post831024

It's because it can't find the LayoutRenderer onexception. But why?!

Tobi had this... maybe it's related to WHS 2011?

**Comment by tlindener** [comment]
Here's another one from my WHS 2011

Service cannot be started. System.TypeInitializationException: The type initializer for 'MPExtended.Libraries.General.Log' threw an exception. ---> NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\Program Files (x86)\MPExtended\Service\NLog.config ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on File Target[fileExtendedInfo] ---> System.ArgumentException: LayoutRenderer cannot be found: 'onexception' at NLog.Config.Factory`2.CreateInstance(String name) at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, Tokenizer sr) at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, Tokenizer sr, Boolean isNested, String& text) at NLog.Layouts.SimpleLayout.set_Text(String value) at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory) at NLog.Internal.PropertyHelper.Se...

**Comment by oxan** [comment]
Fix for WHS installations postponed to 0.4.3, there's an untested workaround in the issue-137-nlog-error branch.

**Comment by tlindener** [comment]
The error has changed to "Verify that you have sufficient priviliges" and in the event viewer the exception has changed to:

Service cannot be started. System.TypeInitializationException: The type initializer for 'MPExtended.Libraries.General.Log' threw an exception. ---> NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\Program Files (x86)\MPExtended\Service\NLog.config ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on Console Target[consoleLog] ---> System.ArgumentException: LayoutRenderer cannot be found: 'time'
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, Tokenizer sr)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, Tokenizer sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyF...

**Comment by oxan** [comment]
Full exception details:

http://forum.team-mediaportal.com/threads/updated-24-jan-mpextended-webmediaportal-0-4-2.103881/page-23#post-845984

**Comment by oxan** [comment]
We can't fix this for 0.4.x as we'll need a complete new logging framework and @DieBagger opposes using a custom self-made logger.

**Comment by oxan** [comment]
And we got rid of NLog, so it can't fail anymore either.
