### ISSUE TITLE
Port TV4Home TVViewer to MPExtended

### ISSUE THREAD

**Issue by tlindener** [MPExtended/MPExtended#138]
- add vlc as player
- add epg view
- move logic from views to more generic design (may be)

**Comment by tlindener** [comment]
Currently i'm slowed down due to several issues with a new epg view. Should we leave it out for now and focus on providing the basic application or should we postpone it(again)?

My vote is for the first option...

**Comment by oxan** [comment]
Yeah a first version without EPG is fine in my opinion.

**Comment by tlindener** [comment]
Okay great, then i will focus on this first!
