### ISSUE TITLE
Check performance of specialized WebChannel objects

### ISSUE THREAD

**Issue by tlindener** [MPExtended/MPExtended#139]
For the TVViewer it could be useful to have an extended WebChannel class which not only contains the channel but also corresponding program lists.

Now it would be useful to know whether it's better to generate it at the service or at the client.

**Comment by oxan** [comment]
Didn't we already have a method to get current/next programs in a channel list?

**Comment by tlindener** [comment]
It's not about current/next but about a model which includes are certain timespan of program objects.

**Comment by oxan** [comment]
Ah, you mean a combined GetChannelsBasic and GetProgramsBasicForChannel?

**Comment by tlindener** [comment]
Yeah exactly!

**Comment by oxan** [comment]
Seems fine, even though doing it in the client doesn't cause much delay (I do that in the WebMP TV guide for example).

**Comment by tlindener** [comment]
Any favorite?

**Comment by oxan** [comment]
No.
