### ISSUE TITLE
Support DVD files

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#14]
Support DVD files:
- Image extraction doesn't work yet. Gives a few exceptions because ffmpeg fails. 
- Does VLC pick them up?

At least moving pictures saves them as path to the .IFO in the database

**Comment by lyfesaver** [comment]
IMO, this could be pushed to 0.6

**Comment by oxan** [comment]
http://forum.team-mediaportal.com/threads/mpextended-service-0-5-0.114105/page-10#post-937579
http://forum.team-mediaportal.com/threads/mpextended-service-0-5-0.114105/page-10#post-938150
