### ISSUE TITLE
Download channel logos from client if possible

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#145]
With the service discovery in 0.5, where the TAS knows to find a MAS, what about making it automatically fetch TV logos from MAS and using them? Ideally MP saved them on the TV server too but that's not the case unfortunately.

**Comment by tlindener** [comment]
I don't think that's a good idea because MAS always needs to be online. And then it's not clear for the user that they have to place the icons in both locations.

**Comment by oxan** [comment]
Well yeah, but we should cache them on the TAS installation. I actually imagine it a bit more like this:
- TAS discovers a MAS installation on the local network (in a background thread)
- TAS asks the MAS installation for the channel logos that it can't find locally
- TAS then writes these logos to a cache directory
- If the client asks for a channel logo and TAS can't find it in MediaPortal's directory, it loads it from the cache directory (if available there of course) instead of failing.

This doesn't require MAS to be online when channel logos are asked, just requires it to be online _once_. And it isn't clear to our current users that they should copy the logos to the server either.

**Comment by DieBagger** [comment]
Hm, I think this is getting too complicated... How about a simple button "Import Tv Logos" instead of having a complicated automatic downloading and caching process?

**Comment by oxan** [comment]
I already have a working implementation that's about 50 lines of code. That branch contains some more stuff like #186, #62, #98, #145, #51 and #41. I've been wanting to write a summary of the changes and get it merged for some time now, but didn't find the time yet.
