### ISSUE TITLE
Support for Myfilms plugin

### ISSUE THREAD

**Issue by z3us** [MPExtended/MPExtended#147]
Could u add support for MyFilms?
I add an example of movies DB. It contains path of videofiles, covers, actors, sinopsis, translated title, original title, year, etc.
Also I attach an sample of MyFilms config File (\ProgramData\Team MediaPortal\MediaPorta\MyFilms.xml) . It has the path to the movies DB
Thanks

http://www.multiupload.com/TGQM8Z5SDF

**Comment by oxan** [comment]
Could you upload them again? It looks like multiupload is down...

**Comment by z3us** [comment]
Of course.
Here you have:
http://www.mirrorcreator.com/files/UKA7B5NX/pelis.xml_links
http://www.mirrorcreator.com/files/YCGQ5SZT/MyFilms.xml_links

**Comment by oxan** [comment]
Great, thanks.

I still've one question though. The database references pictures for most movies, but they only give the file name and not the path. Can you give me the full path to images like Rise of the Planet of Apes.jpg or Drive.jpg? I think they should be somewhere in C:\ProgramData\Team MediaPortal\database\ or C:\Users\nacho\Videos\pelis.

**Comment by z3us** [comment]
I have set this in myfilms.cfg:
    entry name="PictureHandling">Relative Path</entry>

So the pictures are stored  here:
  entry name="AntPicture">C:\ProgramData\Team MediaPortal\MediaPortal\database\MyFilms</entry>"

I have never used full path setting, but I think that in this case, the path would be stored inside the films DB file
Anyway, I hope that today or tomorrow  a MyFilms developer is claryfing this

**Comment by GuzziMP** [comment]
Hi oxan,
MyFilms supports a lot of different external catalogs - and thus different configs not only for artwork.
It also supports multiple configs with different catalogs and/or settings - so it is probably best to define an API to retrieve that info!?
There is a public methos to get all movies from MyFilms with their respective config already - e.g. Trakt is using it.

```
        // get all movies
        ArrayList myvideos = new ArrayList();
        BaseMesFilms.GetMovies(ref myvideos);
        TraktLogger.Info("BaseMesFilms.GetMovies: returning " + myvideos.Count + " movies");

        List<MFMovie> MovieList = (from MFMovie movie in myvideos select movie).ToList();
```

THis method however returns you a list of all movies, but does not populate the Picture (as it is too timeconsuming to do that for all movies instantly).
There is a private method returning full path for image, so depending on how an implementation is planned, such a method could be made public - or we just add another one better fitting the needs.

**Comment by oxan** [comment]
Hmm yes, I should take a look at the MyFilms API itself. For all plugins we are parsing the database itself, usually because the plugin library is just too slow. We load the whole movie list _a lot_ (in facta, too much), so we really want it to complete it in <0.1 second. I didn't check the MyFilms API yet, as the XML format seemed quite easy to parse. 

Basically what we need is quite simple. It's just one method, that gives us all movies and it's information: id, path, title, year, runtime, rating, date added, genres, actors, imdb id, description/summary, director, tagline and writers. I think this is already provided by the current API. It would be nice if it could also give some indication whether artwork is available or not. The loading of the actual artwork itself can be in a different method and is allowed to be a bit slow (we've some other plugins that download them from the internet on demand). I think it's the easiest for us if there is a method that returns a path or an URL to the artwork. 

I'd be nice if there also were methods to retrieve just one movie and all genres, but we can deduce that information from the main list of movies  (as these methods aren't very performance critical).

**Comment by GuzziMP** [comment]
Re parsing DB itself:
You can do that, yes, format is quite easy - but in that case, you'd have to load the config (MyFilms.xml) and ther might be multiple databases. So you end up in reimplementing som of the logic to handle multiple configurations and their databases.
This is "hidden" behind the mentioned method, as it will read all configs and return content of those the user configured to be allowed to show on API.
Re performance: FOr bigger DBs, no chance to get <0.1 secs.
I do internal caching via msdataset for that purpose - first load from XML takes 2 seconds for that - when reading from memory, it is 0.1 - 0.2 seconds - but the API currently does NOT cache the data to avoid the memory consume for that.
However, I could add that as an option, if performance is an issue. It would also reduce IO a lot, if you load that data often.
(For small catalogs/DB runtime isn't an issue of course - I just wanted to mention my testcase with 10k movies and 150k persons ...)

Re "artwork available" indicator: That is all a questioj of runtime - would be nmo problem to e.g. make an overloaded versions, that e.g. returns that information - or even returns the "basic artwork" (that's probably possible fast). BUT: Availability as only possible if IO checks are done (we can't be sure, if it is true, what's in the DB, artwork could have been removed from disk) - and IO usually is slow (internally for MyFilms itself I moved the artwork loading into a separate BG thread, as it will do a lot to search for possible artwork and fallbacks).
So conclusion could be to use something like GetMovies(ref arraylist movies, bool getartwork) - so you can decide if you want slow version with artwork or faster one without.

Re MovieDetails: No prob to provide such method containing more details info - but as you said, can be taken from movielist too (and add things, as needed).

If you want to make a test, you could also use the "RecentlyAddedAPI":
        /// <summary>


        /// returns the most recent movies based on conditions
        /// </summary>


        /// <param name="type">most recent type</param>
        /// <param name="days">number of days to look back in database</param>
        /// <param name="limit">number of results to return</param>
        /// <param name="unwatchedOnly">only get unwatched episodes (only used with recent added type)</param>
        public static List<MFMovie> GetMostRecent(MostRecentType type, int days, int limit, bool unwatchedOnly)
That one will internally use the GetMovies and add and return artwork for the limited return set.

**Comment by oxan** [comment]
Yes - using the MyFilms API will definitely be easier. I don't really mind doing some extra work though: I don't think MyFilms will even get close to the amount of workarounds needed for some other plugins. 

About 2 seconds for loading 10.000 movies seems very reasonable to me. There aren't a lot of people who have that much movies, and from experience I know that other parts of MPExtended already get in trouble with about 1500 movies, so I think the performance is fine. It'd be nice if the API could cache, but doing it in MPExtended is quite easy too, so you shouldn't worry too much about that. 

We don't really need to be sure that the artwork exists on disk. We have some more checks later on in the code before we access it, so it's safe if it says that there is artwork available but in fact there isn't. The only usage of the artwork indication is to avoid filesystem lookups for paths that don't exist :) So if you could've an overload that just returns the "basic artwork", that would be great. 

I'll do some tests with your current API tomorrow and report back here.

**Comment by GuzziMP** [comment]
Re caching: tbh, I would prefer to do caching on MPE side - as MPE knows better when to release memory or when not - and you're right, it's not difficult anyway.
If you want me to add it to MyFilms, I'd probably also do that with an overload - that way, for "normal operations" the memory footprint doesn't get too high - and for users using it with MPE it can be used and users have to take care about enough memory.
Re artwork: That's fine - if you only need artwork location without verification, it should be really fast, as the IO operations are not needed.
Do you want path to original artwork or path to cached thumbs (smaller, faster, but less quality)?

**Comment by oxan** [comment]
Sorry, I've been a bit busy lately so didn't look at the MyFilms API until today.

Aside from the actual API, there is another problem with directly using the MyFilms code: we cannot reference the MediaPortal client assemblies, such as Core.dll and Dialogs.dll, which are required by MyFilms... These assemblies reference some DirectX stuff, which we can't load because MPExtended runs as a Windows Service. Aside from that, I'd prefer to don't have to ship the whole MediaPortal core ourselves too.

**Comment by z3us** [comment]
Any news about this? Is it an impossible task?

**Comment by oxan** [comment]
No. 

It looks like we can't merge any code using MP plugins directly for at least 0.5, so I'd have to use my own parser. I'm a bit reluctant to merge it though, as it supports only one of the database layouts used by MyFilms.

**Comment by oxan** [comment]
Done now.
