### ISSUE TITLE
Breadcrumb for WebMediaPortal

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#151]
A breadcrumb so the user can quickly go back to previous pages. See MediaPortal homepage for a nice implementation.

**Comment by lyfesaver** [comment]
You can assign this to me if u want. I can do this easy for the default skin. No changes needed outside the view.

I think most skins (much like jQui) in the future will be have in some way where breadcrumbs are not needed. But the very controlled structure of the non edited WebMP and default skin makes breadcrumbs VERY handy.
