### ISSUE TITLE
HTTP Live Streaming segmenter crashes too much

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#16]
The HTTP Live Streaming segmenter crashes way too much to be useful.

**Comment by oxan** [comment]
FMI: apparantly ffmpeg also has a segmetner

**Comment by oxan** [comment]
That's since the 0.9 release. We should update ffmpeg (#101) and then use that for segmenting.

**Comment by augustinmarx** [comment]
For iDevices (iPhone, iPad) it would be possible to use VLC HTTP Live Streaming, see
http://wiki.videolan.org/Documentation:Streaming_HowTo/Streaming_for_the_iPhone
but this is only working with nightly builds (http://nightlies.videolan.org/)

I successfully configured a iPIMP (V5.1.0.755) streaming profiles for Live TV and Recordings with this technique.
If appreciated, I can provide some info on that.

**Comment by oxan** [comment]
Yeah, with vlc 1.2 that is an option.

**Comment by oxan** [comment]
This is no longer relevant as I'm using the HTTP segmenter from VLC 2.0 now (not that that one is stable either, but anyway). See issue #193.
