### ISSUE TITLE
Add TV Server status page

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#160]
Add TV Server status page

**Comment by tlindener** [comment]
Just a static overview or should it be dynamic?

**Comment by oxan** [comment]
Dynamic. I'd want to list things like this there:
- Active timeshiftings
- Active streaming sessions
- Current recordings
- Etc

**Comment by tlindener** [comment]
I mean should the page itself be dynamic not the listed data.

**Comment by oxan** [comment]
What exactly do you mean with dynamic then? I thought that dynamic meant that it's generated from code.

**Comment by bodiroga** [comment]
Perhaps he is talking about the page itself being refresh dynamically and not only if the user refresh it...

**Comment by tlindener** [comment]
I mean what bodiroga explained ;)

**Comment by oxan** [comment]
Ah well, in that way it can be static (even though updating it on the fly through AJAX would be nice, but it's a lot of work for a minimum gain imo).
