### ISSUE TITLE
Support translations for WebMP and Configurator

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#167]
I think it's quite easy to do this in ASP.NET MVC, not too sure about WPF but I can easily implement something myself if needed. Probably use something like @DieBagger did for aMPdroid to get translations.

**Comment by bodiroga** [comment]
Great Oxan, looking forward to help with the spanish translation ;-)

**Comment by tlindener** [comment]
As far as i know there is no "easy" way to localize WPF applications, so it would be best to develop something ourselves.

**Comment by oxan** [comment]
It would be nice if we could set the content of a <TextBlock> to a resource, I think we've covered most of our texts then. Resources are translatable by default.

**Comment by oxan** [comment]
@bodiroga: As this is implemented for WebMP now, you can start translating :)

**Comment by oxan** [comment]
We can do it in the installer too btw.

**Comment by DieBagger** [comment]
Should we start asking users to help with translations?

**Comment by oxan** [comment]
Yes, but first we have to sync the texts from current git master to mygengo, there have been some changes.

**Comment by oxan** [comment]
This done now too.
