### ISSUE TITLE
Add "views" option to Home / Recordings pages

### ISSUE THREAD

**Issue by MrTechno** [MPExtended/MPExtended#170]
At the moment it's just list elements of &lt;title&gt; (&lt;start time&gt;) and you have to follow each link to see a description. It would be nice to have a views dropdown in the style of File Explorer so you can show it as a list, details, maybe even show video thumbnails if the TAS API supports it?

**Comment by MrTechno** [comment]
I'll take this one

**Comment by oxan** [comment]
See also #217.

**Comment by oxan** [comment]
This is implemented with the skinning support and improved default skin now.
