### ISSUE TITLE
Add information about available Artwork to MAS object

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#18]
Add a new class (WebArtworkInfo) to classes that contain artwork (e.g. Movie, TvShow). 

WebArtwork could contain:
- Type of Artwork (Cover, Banner, ....)
- Rating/Priority of artwork
- Maybe simple image information file type/size/resolution?
- Index or Count (depending on implementation)

We could either have one WebArtworkInfo for every item or for each artwork type or one for each type (in which case we would return a Count). I would prefert to have one WebArtworkInfo for each item.

**Comment by oxan** [comment]
I prefer one for each item too. If this is implemented we can do #6 too.

**Comment by oxan** [comment]
And we should standardize naming. Either name it Offset here or rename the offset parameter to index in GetArtwork
