### ISSUE TITLE
Show placeholder for missing artwork on homepage

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#184]
```
[23:52:01] <oxan> anyway the missing artwork is because it isn't present in yoru programdata folder
[23:52:09] <oxan> see for example C:\ProgramData\Team MediaPortal\MediaPortal\thumbs\MPTVSeriesBanners\<...>\Episodes
[23:52:19] <oxan> it ends with 7x14, while the last episode is 7x15
[23:52:24] <oxan> so it doesn't show artwork for 7x15
[23:52:29] <Lyfesaver> fair enough
[23:52:33] <Lyfesaver> thx =)
[23:52:55] <oxan> it'd be nice if we could show a placeholder or something there though
[23:53:04] <oxan> maybe just some fanart of the series
[23:53:13] <Lyfesaver> ya good point
```

**Comment by DieBagger** [comment]
I think instead of fanart we should have a generic artwork for this that shows that there is no episode/movie/tv show artwork available yet. I'm sure one of the mp skins has a nice one we could use for this..

**Comment by oxan** [comment]
Good idea.

**Comment by oxan** [comment]
I've a branch ready for this which I'll merge if someone can give me a good default image (copyright-free or GPL-compatible licensed).

**Comment by lyfesaver** [comment]
okay.. after spending a lot of time with various GPL images that are common around town as a "default image" none of them looked like they belonged in the default skin, some looked "okay" in mine and aredon's, but not so much in default.

So i created some VERY basic images that A) will replace missing artwork, B) helps the user to understand WHY and C) Tells the user how they can correct it. here they are:

http://www.lyfesaver.net/demo/notvPoster.png              @ 680 x 1000
http://www.lyfesaver.net/demo/notvEpisode.png          @ 400 x 225
http://www.lyfesaver.net/demo/notvBanner.png             @ 758 x 140
http://www.lyfesaver.net/demo/nomoviePoster.png      @ 640 x 960

If this not what you want to use, then so be it. It wont hurt my feelings. =)

Furthermore, I would think the best way to handle it is have the dummy images in default  content folder, and these images use a certain name, any skinner can make his own by having them in the skin content folder with the images using the required filename. if none exist for skin, it uses default..

What do you think?

**Comment by oxan** [comment]
I've merged this now with slightly modified images for the homescreen. I think not showing any image at all is better on the other screens. See commit 1c464fc for details.

You can override these files in your skin with files named like Skins/<name>/Content/Images/default/<imagename>.png, where you can lookup the imagename in the diff of the commit linked above.

**Comment by lyfesaver** [comment]
actually, it is the other screens not having an image that causing the jquery issues. Home screen is an easy fix... anyone who can spell html should be able to take care of that.

**Comment by oxan** [comment]
Not in stock WebMP. Anyway, you can actually use different images for the other screens too, I just didn't use that in the default skin. 

For reference, the list of images is:
- movie-cover.png
- movie-fanart.png
- album.png
- tvseason-banner.png
- tvepisode-banner.png
- tvshow-fanart.png
- tvshow-poster.png
- tvshow-banner.png
- logo.png
