### ISSUE TITLE
Move CSS out of the views

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#185]
It's fugly.

**Comment by tlindener** [comment]
Isn't aredon redesigning the views anyway? There shouldn't be any of the old CSS left... 

I'm not 100% sure but while i worked on WebMP i removed all the embedded css but i stopped working on that(and it's in berlin and not here in munich)

**Comment by oxan** [comment]
Well, there is still some left and I need to move it for him. There are some tricks needed to link an external CSS file: I don't really want to dump everything in a global CSS, having per-page CSS is nice.

**Comment by oxan** [comment]
Merged.
