### ISSUE TITLE
Add another logo search directory

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#186]
```
[00:09:40] <Lyfesaver> fyi
[00:09:42] <Lyfesaver> mine are
[00:09:43] <Lyfesaver> in
[00:09:44] <Lyfesaver> C:\ProgramData\Team MediaPortal\MediaPortal\skin\aMPed\Media\Logos\Channels
```

(only in meta-service branch given issue #145)

**Comment by lyfesaver** [comment]
following

**Comment by lyfesaver** [comment]
Hmmmmm, i think this is just a location for skins that WANT to offer channel logos (like aMPed does). But you still have to have them moved over to the right folder and named correctly, so I am not sure paying attn to this folder would do any good. Not sure.

**Comment by oxan** [comment]
It's a one-line change, so I don't think it would be a big problem to add it...
