### ISSUE TITLE
Publish WifiRemote in QR-code and Zeroconf

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#2]
Find a nice way to publish WifiRemote in the QR-code and over Zeroconf, without coupling them too much.

**Comment by oxan** [comment]
See pull request #28 for continuation of this discussion. It would have been nice if you can convert a issue into a pull request.

**Comment by Shukuyen** [comment]
http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github ;-)

**Comment by oxan** [comment]
Afaik you get things like #25 then instead of a proper pull request. I'll try it with fixed sometime though.

**Comment by oxan** [comment]
Doesn't work indeed, see #10

**Comment by Shukuyen** [comment]
meh :-/
