### ISSUE TITLE
Download from WebMP fails on large files

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#202]
Downloading of a webmp file failes for larger files (testet with ~1GB files).

**Comment by lyfesaver** [comment]
Is it just large files? I thought it had to be HD as well. I have some SD content that 1+ GB, but that seems to stream/DL thru does it not?

**Comment by lyfesaver** [comment]
BTW, DieBagger this also occurs during streaming of HD files. The player glitches and quits in the middle of the movie. Using pseudo player and seeking to last place works and usually does not glitch again on 4 or 8GB files.

**Comment by DieBagger** [comment]
Streaming is one thing, but for downloading it doesn't matter if its sd, hd or a bunch of random bits -> data is data...

**Comment by oxan** [comment]
Still needs #203 to get properly fixed.
