### ISSUE TITLE
Support Range headers

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#204]
(That is, resuming downloads in webmp etc). 

I've no clue how to implement this.

**Comment by DieBagger** [comment]
hm, I think the easiest way is to debug it and see what parameter browsers use to signal the start position...

**Comment by DieBagger** [comment]
Check out this article and the source code of it: http://dotnetslackers.com/articles/aspnet/Range-Specific-Requests-in-ASP-NET.aspx

Seems to be a bit more work then I excpected... ;)

**Comment by oxan** [comment]
I know how browsers request ranges, but the service <-> WebMP communication is a bit tricky, just like the Direct streaming mode, where we miss Content-Length too.

That article overcomplicates things imo.

**Comment by DieBagger** [comment]
Especially the source code is very interesting...

The missing content length at the wcf communication is a problem indeed...

**Comment by oxan** [comment]
Yeah, but it is still overly complicated as it also handles stuff like ETag and If-Modified-Since, which aren't really relevant for us now. 

And #96 needs to be fixed indeed (just referencing the issue)...

**Comment by DieBagger** [comment]
I can't really say how relevant these are as I have no idea how/if browsers/dl managers actually use these tags...
