### ISSUE TITLE
Actors information for Series and Movies

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#21]
Provide actors information (id, name, role(s), images) for series and movies providers.

**Comment by oxan** [comment]
Do we want this for 0.4? We should at least think of something to keep it API compatible if we do it later.

**Comment by DieBagger** [comment]
I would say yes for 0.4, we don't need to actually implement it in plugins but at least the api should be ready for it.

**Comment by oxan** [comment]
The basics are implemented in 4b84bf1, so we can now extend it without breaking API compatibility.
