### ISSUE TITLE
Add https support to webservice

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#213]
Add https access also for the wcf webservice itself, so communication with clients like aMPdroid is also encrypted...

**Comment by oxan** [comment]
This is a lot harder to implement than I expected. 
- Creating certificates is usually done with makecert.exe, which only gets shipped with Visual Studio and we can't use in the installer. 
- You need quite some binding configuration to allow for HTTPS requests.
- You need to configure http.sys (why does MS implement HTTP as a kernel-level thing? wtf!) to use the correct certificate, using a procedure that has been designed to be as hard as possible.
- I can't get it working.

**Comment by DieBagger** [comment]
So I guess we should push this back to a later milestone?

**Comment by oxan** [comment]
Retargeting this to 0.6 accordingly.
