### ISSUE TITLE
bufferlength in jwplayer

### ISSUE THREAD

**Issue by FreakyJ** [MPExtended/MPExtended#225]
let the jwplayer buffer to get smooth video playback
add 'bufferlength': '60',

now it is:
jwplayer('mediaspace').setup({
        'controlbar': 'bottom',
        'width': '800',
        'height': '450',
        'skin': '/Content/jwplayer/slim.zip',
        'modes': [ 
           { type: "flash", src: "/Content/jwplayer/player.swf" } 
        ]
    }).onTime(function (callback) {

than it would be:

jwplayer('mediaspace').setup({
        'controlbar': 'bottom',
        'width': '800',
        'height': '450',
        'bufferlength': '60',
        'skin': '/Content/jwplayer/slim.zip',
        'modes': [ 
           { type: "flash", src: "/Content/jwplayer/player.swf" } 
        ]
    }).onTime(function (callback) {

60 means that the player will buffer 60 seconds, for more details look here:
http://www.longtailvideo.com/support/jw-player-setup-wizard

**Comment by abhiramriet** [comment]
Hi, I am facing issue in playing the JW player in mac firefox the issue is that it continuously keeps on buffering the video, the content is mov.

**Comment by oxan** [comment]
Please open a topic in the MediaPortal forums with your logs attached. It's easier to help you that way.
