### ISSUE TITLE
Make WebMP more extensible 

### ISSUE THREAD

**Issue by tlindener** [MPExtended/MPExtended#227]
We should provide better extensibility for WebMP so that we can easier add new views for plugins like mv central.

For now this is just a discussion but i'm quite interested in adding this feature in the long term development of WebMP.

**Comment by oxan** [comment]
I'm not sure why we would need new views for mvCentral. it's a music plugin like all others, so it should work with the default music views (which it does, except for people who don't load album information, but that's their own fault).

**Comment by tlindener** [comment]
It's just an example for a plugin for which certain additional views could be interesting.

I explicitly don't mean we have to change something in the backend, but i think it would be interesting to be able to add additional tabs to WebMP based on plugins.

As i said it's only an idea - so if no one is interested i'm not pissed ;)

**Comment by lyfesaver** [comment]
saw this when i was looking for the missing artwork issue... and would like to add my two cents.. the more extendable the better, but from people that have sen the code that i have introduced to the project (trevor, gloomer, etc) have been extremely pleased with how it currently is. Does it need to be more? I can't answer that. But I would like to say that mvC is more than just a music view, as it needs video playback. But u already know this =) so i digress

**Comment by oxan** [comment]
I've implemented this now with merge 2918d7d, though it needs a lot of documentation.
