### ISSUE TITLE
Have mvCentral switch to using video player, not audio.

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#232]
Title says it all, but basically as it stands, mvCentral uses the MP3 flash audio, not video.

**Comment by lyfesaver** [comment]
Also, it would be best (imo) to have the mvC plugin be separate from the mymusic plugin... as some will have a mp3 collection and a music video collection. Right now i believe it is one or the other.

**Comment by lyfesaver** [comment]
worst button placement ever... the close and comment button....

**Comment by oxan** [comment]
Yes, I do that wrong all the time too :/

**Comment by oxan** [comment]
Actually, this [the implementation] sucks a bit, as we don't have per-song pages anymore and don't have a way to communicate between the mvCentral plugin and WebMP that it wants a video player instead of an audio player.

**Comment by lyfesaver** [comment]
Ahhh ya that would make sense
