### ISSUE TITLE
Add feature to MPE to fetch RT CPU usage

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#234]
It would be nice, but FAR from needed, to show a simple stack bar graph to reflect real time CPU usage. In other words... a CPU meter of the server u are on.

**Comment by lyfesaver** [comment]
Inker laid it out for me. Works great. here is the code so u can merge, if u want (WebMP code only)

StatusController -

---

using System.Diagnostics;
using MPExtended.Applications.WebMediaPortal.Code;
using System.Web.Mvc;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
    [ServiceAuthorize]
    public class StatusController : BaseController
    {

```
    static PerformanceCounter cpuCounter = new PerformanceCounter();

    static StatusController() {
        cpuCounter = new PerformanceCounter();
        cpuCounter.CategoryName = "Processor";
        cpuCounter.CounterName = "% Processor Time";
        cpuCounter.InstanceName = "_Total";;
    }

    public ActionResult Index()
    {
        return View();
    }

    public JsonResult RetrievePerformanceCounters() {
        return Json(new {CPU =  cpuCounter.NextValue()}, JsonRequestBehavior.AllowGet);
    } 
}
```

}

Views/Status/Index.cshtml - 

---

http://paste2.org/p/2041270

could not paste the html code here as it wanted to apply the text as actual formating for this comment, lol

**Comment by lyfesaver** [comment]
I just remembered... do add this u would need to add the controller like i have done... and that got me thinking... do u want any of my work to be merged? 

P.S. (Oxan knows this so this is more for anyone else that might read this) I dont exactly feel comfortable calling it "my work", when it was Oxan and Inker who did most of it. I just want that noted.

**Comment by oxan** [comment]
This has been merged nowadays (don't remember the commit).

**Comment by lyfesaver** [comment]
"nowadays" wow.... try not to get so technical =) hehe
