### ISSUE TITLE
Support transcoding via handbrake

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#247]
http://handbrake.fr/

Open source video transcoder with cli: https://trac.handbrake.fr/wiki/CLIGuide

Also it seems that handbrake might be the best option to get GPU-supported transcoding in the near future: http://www.anandtech.com/show/5835/testing-opencl-accelerated-handbrakex264-with-amds-trinity-apu

**Comment by oxan** [comment]
It might work already with the Generic transcoder (merged a few days ago):

```
<transcoder implementation="MPExtended.Services.StreamingService.Transcoders.Generic">
   <transcoder>C:/Path/To/HandbrakeCLI.exe</transcoder>
   <arguments>-i #IN# -o #OUT#</arguments>
</transcoder>
```

Something like that. You can also #WIDTH#, #HEIGHT#, #AUDIOSTREAMID# and #STARTPOSITION# for substitution.

**Comment by oxan** [comment]
I think we need to discuss which transcoders we want to support and use out-of-the-box after the 0.5 release, as we can't keep adding transoders indefinitely.
