### ISSUE TITLE
Create a good set of streaming profiles

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#248]
We need to look at our streaming profiles and decide which ones we want to use for the public release. Currently there are many different profiles we used for testing/development.

We should create video streaming profiles for
- Flash video streaming (webmp) -> We should use the pseudostreaming profile as it allows seeking
- Direct video streaming via e.g. vlc
- Android video streaming
- iOS video streaming? -> Also available for android devices > 3.0

Each profile should be available in 3 (or better 4) different qualities. We need to do testing (ideally with a small group of beta-testers) to make sure this profiles work well.

How about audio profiles?

**Comment by DieBagger** [comment]
Here's an initial take on streaming profiles for vlc/ffmpeg and hls (each with 6 different qualities):http://pastebin.com/raw.php?i=yBG7wJY3

Still needs some refinement (max video size + bandwidth) and some testing.

**Comment by oxan** [comment]
We've pretty good profiles in Git now.
