### ISSUE TITLE
Current Version not compileable...

### ISSUE THREAD

**Issue by jogibear9988** [MPExtended/MPExtended#250]
The current version is note compileable...

This is patch to fix it: https://gist.github.com/3550227

**Comment by oxan** [comment]
This is because we've made ILMerge required to compile the installers. I might reconsider that or make it optional, but for now that's the easiest way to get it working. Your fix actually ends up with a broken PowerSchedulerPlugin, as it needs some MPExtended libraries to be installed too.  

The Transformations change seems unrelated. Afaik that has already been fixed (at least I can compile current master without problems).

**Comment by oxan** [comment]
Solution can be compiled without ILMerge now.

**Comment by jogibear9988** [comment]
I still cannot compile when leaving the Transformations class internal!

I got the error: The access to ...Transformations is not possible cause of the security level!

Here the error:  Inkonsistenter Zugriff: Rückgabetyp "MPExtended.Libraries.Service.Config.Transformations.Transformation" ist weniger zugreifbar als Methode "Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read12_Transformation(string)"

**Comment by jogibear9988** [comment]
And how can I compile using ILMerge? Do I only need to install it, and then it will be used during the installer compile?

Because I think, i require it for WebMediaPortal, because after installation it's missing a lot of it's dlls...

**Comment by jogibear9988** [comment]
The last comment can be ignored, i saw, ILMerge was automaticly used after installatin...

**Comment by oxan** [comment]
You don't need ILMerge for WebMP, but only for the PowerSchedulerPlugin. Anyway, just installing it is fine indeed.

For the Transformations error, which version of Visual Studio do you use?

**Comment by jogibear9988** [comment]
vs2010!

Am 01.09.2012 um 16:13 schrieb Oxan van Leeuwen notifications@github.com:

**Comment by jogibear9988** [comment]
but i've vs 2012 installed, and that means also .net4 is updated! maybe that is the problem?

Am 01.09.2012 um 16:13 schrieb Oxan van Leeuwen notifications@github.com:

**Comment by oxan** [comment]
Hmm, that might cause it. I'm going to do a bit of research ;)

**Comment by oxan** [comment]
The sgen.exe from VS2012 seems to fuck up with compilation indeed. Changed it to public now, seems to work :)
