### ISSUE TITLE
Allow installation of WebMediaPortal when IIS Express 8 is installed

### ISSUE THREAD

**Issue by jogibear9988** [MPExtended/MPExtended#251]
When you install VS 2012 IIS Express 8.0 is installed.

WebmediaPortal will not install.

Here is a fix for this...

Patch for this:

https://gist.github.com/3565371

**Comment by oxan** [comment]
Thanks, merged with some slight changes. :)

(It'd be even easier if you could submit a pull request instead of a patch, but this is fine too ;))
