### ISSUE TITLE
Authentication.xml reset to default

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#253]
It happens quite often that suddenly all user accounts are gone because the Authentication.xml file has been reset to default... 

The logs show this line which is causing the issue:

WARN: Failed to deserialize Authentication.xml, replacing with default file (error: The process cannot access the file 'C:\ProgramData\MPExtended\Authentication.xml' because it is being used by another process.)

What probably happens is this:
- Service tries to read Authentication.xml but fails because some other process has an exclusive handle on the file
- ConfigurationSerializer thinks that the config xml is invalid
- Instead of ignoring that or using the last known configuration, the service overwrites the current config (which is perfectly fine) with the default one... 

Strange is that while it couldn't open the file for read a few moments ago, now it can even delete the file. So it's probably a timing-issue.

**Comment by oxan** [comment]
I fixed this; but Github went down while I pushed it and forgot to close the issue.. Meh.
