### ISSUE TITLE
Add number of seasons to GetAllTVShowsDetailed

### ISSUE THREAD

**Issue by Shukuyen** [MPExtended/MPExtended#265]
Feature request:

It would be useful to know how many seasons a tv show has without having to make an extra HTTP request. The reason for this is so that in a client you could directly jump to the episode list if there is only one season, otherwise you would show the season list.

I know I could call `GetTVSeasonCountForTVShow` for each show but that would be one additional request per show which has quite the performance impact in low connectivity scenarios.

**Comment by oxan** [comment]
I'd have to check what the performance impact of calculating the number of seasons is on loading the list of shows (looks like it can't be easily done in SQL), adding a "SeasonCount" field to WebTVShowDetailed would be fine with me then.
