### ISSUE TITLE
GetTVShowsBasic vs GetAllTVShowsBasic (docs bug)

### ISSUE THREAD

**Issue by Shukuyen** [MPExtended/MPExtended#266]
The documentation at http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/17_Extensions/Remote_Access/MPExtended/Developers/API_Documentation/MAS#GetTVShowsBasic lists the method `GetTVShowsBasic` but it should actually be `GetAllTVShowsBasic`, I think.

Same for `GetTVShowsDetailed`.

**Comment by DieBagger** [comment]
This seems to already be updated for the 0.5 release, where we removed the "GetAllXXX" syntax. Instead you now have GetXXX and GetXXXByRange for all (if we didn't miss any ;)) items.

**Comment by Shukuyen** [comment]
Oh ok, then I am developing with an old version -.- Good to know :D
