### ISSUE TITLE
GetArtworkResized for high rated TVShow poster fails

### ISSUE THREAD

**Issue by Shukuyen** [MPExtended/MPExtended#268]
When requesting posters for TVShows with a rating > 1 mp-extended isn't able to find the corresponding image resource on the hard disk.

Judging by the logs the problem could be that it looks at the wrong path, the first character of the TV show name is cut off. So instead of "\Burn Notice-langen-posters" it will try to request  (or at least logs) "\urn Notice-langen-posters":

```
12:08:57.29261 [<26>] Tried to stream image from non-existing source mediatype=TVShow provider= id=80270 filetype=Poster offset=4 path=C:\ProgramData\Team MediaPortal\MediaPortal\thumbs\MPTVSeriesBanners\urn Notice\-langen-posters\80270-5.jpg
```

The TVSeriesDatabase4.db3 contains this entry for PosterFileNames:

```
Burn Notice\-langen-posters/80270-5.jpg|Burn Notice\-langen-posters/80270-2.jpg|Burn Notice\-langen-posters/80270-1.jpg|Burn Notice\-langen-posters/80270-3.jpg
```

**Comment by oxan** [comment]
Strange, doesn't happen with my database... Any chance you can send me (in private, if you want) your TVSeriesDatabase4.db3?

**Comment by Shukuyen** [comment]
Sure, will upload it later today! 
Thanks for looking into this.
