### ISSUE TITLE
iPad streaming is broken

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#283]
The iPad doesn't seem to accept our streams. I'm not sure how we can fix this though.

http://forum.team-mediaportal.com/threads/mpextended-service-0-5-0.114105/page-2#post-935832

**Comment by oxan** [comment]
http://forum.team-mediaportal.com/threads/mpextended-service-0-5-0.114105/page-2#post-935965

**Comment by oxan** [comment]
http://forum.team-mediaportal.com/threads/mpextended-service-0-5-0.114105/page-7#post-936681

**Comment by Ollienator** [comment]
I can confirm that changing the following in hlsplayer.js is working on the iPad:

``` javascript
var html = "<video src='" + data.URL + "' width='" + $("#hlsplayer").width() + "' height='" + $("#hlsplayer").height() + "' controls='controls' autoplay='autoplay'>Your browser does not support the video tag</video>";
```

Unfortunately I dont have an iPhone or iPod touch to cross check.

**Comment by oxan** [comment]
Awesome, thanks! I'll get it cross-checked ;)
