### ISSUE TITLE
Reverse proxies and port forwards break absolute URLs

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#324]
Maybe try to use the Host: value as the host?

**Comment by Ollienator** [comment]
Absolute URLs work for WebMP when reverse proxying in IIS, if you use response rewriting.  I was going to write up a guide using IIS and ARR / URL Rewrite, but I need to get Ampdroid working first (awaiting source to find out just how it's communicating with MPExtended).
The reverse proxy setup has a huge advantage over port forwards as everything goes through port 80, so it's a lot more firewall friendly. ;-)

**Comment by oxan** [comment]
Yes, I agree, but it's not possible to use a reverse proxy for everyone and not everyone knows how to setup one.

**Comment by oxan** [comment]
We already write the Host: header from the client in the playlist file, that 8bb8a65 adds it for HLS too, so should be solved now (that are our only absolute URLs).

**Comment by Ollienator** [comment]
I have just committed 1eba846 that allows overriding  the base URLs returned by MPExtended/WebMp.  Using the request header didnt work reliably for reverse proxy scenarios.

**Comment by oxan** [comment]
While I'm not opposed to your commit (I'll try to find some time to merge it tomorrow), I'm curious in what scenarios it didn't work reliably?

**Comment by Ollienator** [comment]
doing reverse proxying using iis arr / url rewrite, both json responses and playlists still contained internal urls.  this was addressed by using response rewriting rules, but response rewriting made it complicated and especially for large json responses, unrealiable.  just came across the json issue today when trying to get ampdroid to work again.  
anyway, if left unconfigured, those options shouldnt do any harm as they just fall back to standard behaviour.

**Comment by oxan** [comment]
Ah yes, that makes sense. I've slightly modified your patch a bit to use the existing ServiceAddress option in WCFUtil, that one was intended to have the same function as ExternalRootUrl in your patch, but the implementation was broken. I've merged the WebMP part as-is.

I've also cherry-picked some of your previous commits and committed an alternative implementation of the HLS-artwork commit. Thanks very much!
