### ISSUE TITLE
Add option to choose service IP address

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#343]
Autodetection doesn't seem to work all the time.

**Comment by oxan** [comment]
Configuration option implemented in 160a0c7.

**Comment by oxan** [comment]
Do we really need a user interface for this? I don't think much people who will need this won't be able to change the XML.

**Comment by DieBagger** [comment]
If many people request it we can add the ui later on...

**Comment by oxan** [comment]
Sounds good.
