### ISSUE TITLE
Loading IP address from whatsmyip.com triggers .NET bug? 

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#344]
http://forum.team-mediaportal.com/threads/updated-3-dec-mpextended-service-0-5-1.114105/page-14#post-941482
http://forum.team-mediaportal.com/threads/updated-3-dec-mpextended-service-0-5-1.114105/page-14#post-941510
http://forum.team-mediaportal.com/threads/updated-3-dec-mpextended-service-0-5-1.114105/page-14#post-941518
http://forum.team-mediaportal.com/threads/updated-3-dec-mpextended-service-0-5-1.114105/page-15#post-944068

This is really weird. The exception details from the first post look a lot like some kind of issue inside .NET itself, but I don't see how this can be caused by whatsmyip.

**Comment by DieBagger** [comment]
Maybe we're hitting some timeout in the zeroconf service?

**Comment by oxan** [comment]
You're sure you're not confusing this with #345? This guy has fixed it by disabling external address detection, which isn't related to Bonjour (which he still has enabled, I assume).

**Comment by DieBagger** [comment]
The ip address detection is done in ZeroconfPublisher -> Publish() ... so a delay in the detection of the external ip address might cause issue in the zeroconf service...

**Comment by oxan** [comment]
But it's done before the first call to Bonjour happens, so I fail to see why this can cause a timeout issue in Bonjour.

**Comment by oxan** [comment]
whatismyip.com disabled their service, so doubtful that we still hit this bug.
