### ISSUE TITLE
Streaming is unstable

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#36]
There are still problems with streaming. This is a general issue to track all bugs related to streaming.

**Comment by oxan** [comment]
IRC extract from the last discussion related to the state of streaming:

```
173.    [09:50:53 PM]   <DieBagger_>    about that little issue called streaming
174.    [09:51:00 PM]   <DieBagger_>    what's the current state?
175.    [09:51:26 PM]   <@oxan> i don't really know
176.    [09:51:40 PM]   <@oxan> that is why i opened #36 on github to track it a bit better from now on
177.    [09:51:42 PM]   <DieBagger_>    the "Waiting till output named pipe is ready" bug was already fixed iirc?
178.    [09:52:03 PM]   <@oxan> afaik non-TV streaming works mostly reliable now with the VLCWrapper profile
179.    [09:52:20 PM]   <DieBagger_>    whic vlc variant should I use?
180.    [09:52:36 PM]   <@oxan> VLC Long Profile Wrapper Test was afaik the only one with working seeking
181.    [09:53:14 PM]   <@oxan> for tv streaming; i think it worked sometimes but failed to start the stream other times
182.    [09:53:21 PM]   <@oxan> and we still had media_error_unknown with that afaik
183.    [09:53:54 PM]   <@oxan> as for waiting till output named pipe is ready; iirc I've commited a bugfix but untested as i can't reproduce it myself
184.    [09:55:30 PM]   <DieBagger_>    i couldn't get flv streaming to work btw
185.    [09:55:50 PM]   <DieBagger_>    one issue was that the stream needs authentication, but even with that disabled it wouldn't work
186.    [09:56:07 PM]   <@oxan> doesn't really surprise me
187.    [09:56:17 PM]   <@oxan> i haven't looked at the flv streams for a few months
188.    [09:56:55 PM]   <DieBagger_>    hm, I think I ran into the namedpipe thingy again just now
189.    [09:59:06 PM]   <@oxan> hmm, could you send me logs again
190.    [10:03:25 PM]   <DieBagger_>    http://pastebin.com/raw.php?i=P6duwhMu
191.    [10:03:48 PM]   <DieBagger_>    the last one failed, before it worked a bunch of times (seeking)
192.    [10:04:46 PM]   <@oxan> and it just keeps hanging there?
193.    [10:05:10 PM]   <DieBagger_>    yeah
194.    [10:09:33 PM]   <@oxan> hmm I think i might know the reason, i'll see if i can come up with a fix tomorrow
195.    [10:15:59 PM]   <DieBagger_>    ok
196.    [10:16:05 PM]   <DieBagger_>    anyhow the biggest issue is tv
197.    [10:18:51 PM]   <@oxan> yes
```

**Comment by oxan** [comment]
We should handle failure of GetMediaInfo() more gracefully (just assume 16:9 probably). Currently crashes with this exception: http://pastebin.com/raw.php?i=m820pAF4

**Comment by DieBagger** [comment]
When using VlcManaged to stream live tv a lot of these excpetions get logged:

2011-11-08 15:15:19.3403 [VLCInfoThread(18)] WARN: Called NewPercentage(2781,96557617188) but duration is unknown!
(ThreadHelper.ThreadStart_Context => VLCManagedEncoder.InfoThread => TranscodingInfoCalculator.NewPercentage)

**Comment by DieBagger** [comment]
FinishStream can't be called when using VlcManaged, the method times out when called from the client.

**Comment by oxan** [comment]
That first one is just a major logic screw up by me. The second is more or less a bug in VLC. Use VLCWrapper for now, VLCManaged has some issues and doesn't offer any new features. Unless it improves significant we shouldn't ship a transcoder that uses it in the release.

**Comment by oxan** [comment]
As for the waiting-till-pipe-is-ready error; have you also encountered it with VLC Pure?

**Comment by oxan** [comment]
Use doubles for passing percentages between MPExtended and VLCManaged

**Comment by oxan** [comment]
Current logcat from TV streaming: http://pastebin.com/raw.php?i=855cFMXS

RetrieveStream probably doesn't return fast enough which kills Android's mediaplayer. Should be fixable :)

**Comment by oxan** [comment]
Not entirely solved but it's better now. This will probably keep to be an issue for the following months or so.
