### ISSUE TITLE
Guest downloads

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#369]
Enable downloads for specific files for guest users. A logged in user can generate a link that  he/she can send to a 3rd party. This link is valid for x hours and allows download of the given file without user credentials.
- Should be a special permission in the 0.6 permission system (not every user should be allowed to generate these links)
- At the creation of a link we should ask the user how long the link should be valid (e.g. 24 hours, one week, forever,...)
- Should be logged to the "activity" tab in the configurator (showing the ip address of the donwloader?)

**Comment by oxan** [comment]
See webmp-token-downloads branch :)
