### ISSUE TITLE
Re-evaluate choice for hardcodet.net WPF icon

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#376]
It's license is GPL-incompatible, and it has crashes like this: http://forum.team-mediaportal.com/threads/updated-3-feb-mpextended-webmediaportal-0-5-3.114106/page-23#post-963738

**Comment by DieBagger** [comment]
Any alternatives that are gpl compatible?

http://wpfcontrib.codeplex.com/wikipage?title=NotifyIcon&referringTitle=Home
or
http://www.codeproject.com/Articles/36468/WPF-NotifyIcon

both seem to have incompatible licenses...

**Comment by oxan** [comment]
This is also the third report I get of a Win32Exception in the WPF icon I don't understand: http://forum.team-mediaportal.com/threads/updated-3-feb-mpextended-service-0-5-3.114105/page-29#post-1011293

Haven't looked at the alternatives yet, but the WPFContrib one seems to be licensd Ms-PL, which is fine iirc, while codeproject usually isn't.
