### ISSUE TITLE
Install service error

### ISSUE THREAD

**Issue by realper** [MPExtended/MPExtended#377]
I had a problem installing the service.
It was giving the error;
"Service 'mpextended service' (mpextended service) could not be installed. Verify that you have sufficient privileges to install system services"

I used this fix, which resolved the issue, which i huess makes it a confirmed bug:
http://planetmediocrity.com/2010/09/itunes-10-installation-problem-and-solution/

Another blog post i stumbled upon, during my search for a fix:
http://angledontech.blogspot.dk/2011/09/wix-troubleshooting-verify-that-you.html

**Comment by oxan** [comment]
Ok, but I've no idea what causes this. I'm afraid the only way we'll be able to fix this is if you can reproduce it with more verbose logging enabled. You can do that by running this command from an administrator Command Prompt:

```
msiexec /lvoicewarmupx* <full path to a logfile> /i <full path to installer>
```

**Comment by oxan** [comment]
Closing because lack of response. Please open a forum topic with more information if you've any problems.
