### ISSUE TITLE
Support for UNC paths

### ISSUE THREAD

**Issue by scythe000** [MPExtended/MPExtended#380]
MPE will not stream files if the plugin has the DB location configured with a UNC path.

**Comment by oxan** [comment]
UNC paths are already supported in 0.5.x, and mapped network drive support has been added in master. However, if the drive requires authentication, you need to configure that in the configurator (which unfortunately needs the same username and password on both client and server at the moment).

**Comment by oxan** [comment]
Or, on second thought, if you mean that we don't support having the databases on a network drive/UNC path, that's correct. Not only streaming is broken then though, nothing works. You can work around that by configuring the service to run as another user currently.

**Comment by scythe000** [comment]
I had tried that as well, per your direction in my thread, but it didn't work either.

Sent from my iPhone

On Feb 17, 2013, at 9:11 AM, "Oxan van Leeuwen" <notifications@github.com<mailto:notifications@github.com>> wrote:

Or, on second thought, if you mean that we don't support databases on network drives, that's correct. Not only streaming is broken then though, nothing works. You can work around that by configuring the service to run as another user currently.

**Comment by oxan** [comment]
Ok, upload your logs somewhere then please.

**Comment by scythe000** [comment]
Will do.

Sent from my iPhone

On Feb 17, 2013, at 9:18 AM, "Oxan van Leeuwen" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, upload your logs somewhere then please.

**Comment by oxan** [comment]
Closing because lack of response. Use the forums for further troubleshooting; only confirmed bugs here please.

**Comment by scythe000** [comment]
Oh, sorry! I thought I was waiting for a reply from you and missed a notification. What can I do to help troubleshoot this bug?

Sent from my iPad

On Mar 22, 2013, at 11:40 AM, "Oxan van Leeuwen" <notifications@github.com<mailto:notifications@github.com>> wrote:

Closing because lack of response. Use the forums for further troubleshooting; only confirmed bugs here please.

**Comment by oxan** [comment]
As per my last comment; I'll need your logs. If you have an account on the MediaPortal forums, it's a bit easier if you can post it there.

**Comment by scythe000** [comment]
I'll get that to you this afternoon, no problem. I thought I had uploaded new logs in our original forum thread.

Sent from my iPad

On Mar 22, 2013, at 11:46 AM, "Oxan van Leeuwen" <notifications@github.com<mailto:notifications@github.com>> wrote:

As per my last comment; I'll need your logs. If you have an account on the MediaPortal forums, it's a bit easier if you can post it there.

**Comment by oxan** [comment]
If you mean [this thread](http://forum.team-mediaportal.com/threads/help-cant-play-anything-db-now-shows-empty.115734/page-2), it doesn't look like there are any open questions left in that thread (apart from the last one). Anyway, just open a new thread with your remaining questions/problems and I'll take a look at it. Support is a bit messy, especially directly after a release when I get a zillion messages; so I sometimes forget one.

**Comment by scythe000** [comment]
Will do!

Sent from my iPad

On Mar 22, 2013, at 11:59 AM, "Oxan van Leeuwen" <notifications@github.com<mailto:notifications@github.com>> wrote:

If you mean this threadhttp://forum.team-mediaportal.com/threads/help-cant-play-anything-db-now-shows-empty.115734/page-2, it doesn't look like there are any open questions left in that thread (apart from the last one). Anyway, just open a new thread with your remaining questions/problems and I'll take a look at it. Support is a bit messy, especially directly after a release when I get a zillion messages; so I sometimes forget one.

**Comment by scythe000** [comment]
Posted!
