### ISSUE TITLE
WebMP firewall rule overwritten on update

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#389]
When you have assigned custom ports for WebMP and run an update, the windows firewall rule is reverted to the default port (8080).

**Comment by oxan** [comment]
I'm afraid we can't fix this without writing our own plugin for the installer to set the firewall rules, which I'm not willing to do.

**Comment by oxan** [comment]
This issue applies to the service too, btw.

**Comment by DieBagger** [comment]
Hm, if we were to create a custom action for this, we'd have to create different code for xp and for vista++ it seems...

Some interesting links:
http://stackoverflow.com/questions/8889587/automating-windows-firewall-with
http://www.codeproject.com/Articles/19003/The-managed-classes-to-read-Windows-Firewall-confi
http://www.codeproject.com/Articles/14906/Open-Windows-Firewall-During-Installation
http://www.codeproject.com/Articles/10911/Windows-XP-SP2-Firewall-Controller

**Comment by oxan** [comment]
For reference, the (as usual) overly complicated code Wix uses to create the firewall extension:

http://wix.codeplex.com/SourceControl/changeset/view/12a19c3e6d8ad7cdb410e0f6f9bb681d65ed2436#src/ext/FirewallExtension/ca/firewall.cpp
http://wix.codeplex.com/SourceControl/changeset/view/12a19c3e6d8ad7cdb410e0f6f9bb681d65ed2436#src/ext/FirewallExtension/wixlib/FirewallExtension_Platform.wxi

Anyway, I saw Wix 3.7 has been released, it could be worth a try to test whether they've already fixed it.
