### ISSUE TITLE
Using webmediaportal on iOS (ipad!) missing some buttons!

### ISSUE THREAD

**Issue by matbor** [MPExtended/MPExtended#399]
When using webmediaportal on my ipad the later button and sometimes the earlier button doesn't show up! 

![image](https://f.cloud.github.com/assets/1978503/975445/272d77e0-0677-11e3-929a-e0828133cf0e.jpg)

**Comment by oxan** [comment]
Yeah, 1024px wide is too small for the default skin currently, it requires (if I remember correctly) 1280px minimum at the moment. I'm personally not interested in changing that, so you should probably try to use another skin from the forums.
