### ISSUE TITLE
MP-TVSeries doesn't process user-edited values

### ISSUE THREAD

**Issue by puenktchen** [MPExtended/MPExtended#400]
Prefer user defined genre from tvseries-database over standard genre table
in MPExtended Service.

**Comment by oxan** [comment]
I'm not sure what you mean. You're talking about the TV-Series part, right? We should already use user-defined genres there (actually, the genre list is just a list of all genres associated with a show). Doesn't this work?

**Comment by puenktchen** [comment]
Yes of course i'm talking about TV-Series ;-) Sorry, but i think you're not true with genre.
From my understanding in MPTVSeries.cs you are reading only the column "Genre" from table "online_series"
of the database. This is where TVSeries stores scraped genres by tvdb.com.
If you edit genres in the configuration tool of TVSeries, it is stored in the column "Genre__USEREDIT__" from table "online_series". That's what i like to see first. Why? Lets take an example:
I have a Show "Neon Genesis Evangelion". Scraped by tvdb.com the genres are "|Action|Adventure|Animation|Drama|Science-Fiction|". So it's listet in the same place like "Boardwalk Empire" because of the same genre "Drama". For usability reasons i've edited "Neon Genesis Evangelion" genre to "Anime" only. Works perfectly in MediaPortal, but unfortunately not in WebMP or aMPDroid.

**Comment by oxan** [comment]
Oh, like that. This is a more general problem, namely that we don't process most customized data in the MP-TVSeries database. I don't see that being changed any time soon (the USEREDIT columns don't always exists, which makes it quite hard to read from them. And it's just a horrible design I don't want to put my time into).

**Comment by puenktchen** [comment]
Horrible design :-) Fair enough!
