### ISSUE TITLE
Music albums with multiple artist tags in iViewer not displayed

### ISSUE THREAD

**Issue by MichaelE42** [MPExtended/MPExtended#407]
iViewer does not display music album covers if the files have multiple Artist tags (e.g. if you enter in MP3Tag something like 'Bach|Beethoven'). The reason is that MediaPortal uses all tags for the thumb filename (e.g. 'Bach _ Beethoven- My Favorites.jpg') whereas MPExtended only uses the first artist tag and consequently does not find the thumb file.
Probably the issue exists also in WebMP, but did not check.

I have fixed the issue in MPExtended and will create a pull request for the fix.

**Comment by andrewjswan** [comment]
Fixed in Release 0.7
