### ISSUE TITLE
Remove homepage link

### ISSUE THREAD

**Issue by rogerfar** [MPExtended/MPExtended#411]
Please remove the homepage link: http://www.mpextended.com/

It redirects to a scam site.

**Comment by MrTechno** [comment]
This is pending https://github.com/MPExtended/MPExtended/pull/410

**Comment by oxan** [comment]
None of the developers are active within this project anymore, and the domain expired because of that. 

Does either one of you, or someone else want to take over custody of it? Otherwise, I'll probably just archive the repository to avoid problems this.
