### ISSUE TITLE
Make TvAccess methods similar to MediaAccess

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#50]
- Ranged retrieval for all methods
- Add sorting/ordering

**Comment by oxan** [comment]
Given that this breaks API it should be done _before_ release.

**Comment by DieBagger** [comment]
Absolutely, it wouldn't be a good idea to release the api in an inconsistent state

**Comment by oxan** [comment]
This is a WIP in the tas-api branch now.
