### ISSUE TITLE
Proper implementation of categories

### ISSUE THREAD

**Issue by DieBagger** [MPExtended/MPExtended#54]
Implement categories in mas.

Categories are mapping user-made view defininitions/filters in the plugins.

Imo categories need sub-category support.

**Comment by oxan** [comment]
Removed implemention in 0.4, proper implementation for 0.5?

**Comment by oxan** [comment]
This should be the same categories as used in mopi/tvseries btw, but implementing that caused some headaches.
- WebMP support of course.
