### ISSUE TITLE
Add IIS Express to WebMediaPortal installer

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#63]
Install IIS Express in the WebMediaPortal installer.

**Comment by oxan** [comment]
This is a lot harder than it seems like. MSI chaining sucks (I can't get it to work) and you can't launch an installer from a custom action, which means that embedding it in our installer is hopeless. We can create a self-extracting exe which fires up both installers after each other, but that's really confusing for the user (he wants to install WebMP and gets the IIS Express installer). Problem with this is uninstallation: you can't execute custom code there easily, so the user has to uninstall IIS Express manually. Also, we can't make the IIS Express installer quiet as the user has to agree with a license.

**Comment by oxan** [comment]
Added a warning message when IIS Express isn't installed now.

**Comment by oxan** [comment]
Let's postpone this to 0.5

**Comment by lyfesaver** [comment]
What will installing this on machines with a full installation of IIS 7+ do?

**Comment by oxan** [comment]
There will be a separate installer for full IIS installations. This actually has been requested a few times before but I didn't get to it yet. Created issue #88 for that.

**Comment by oxan** [comment]
I think we'll need Wix 3.6 and it's burn tool to do this easily, so let's postpone it to 0.6.
