### ISSUE TITLE
Add security to the streams

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#70]
Someone who has access to the WebMP host and knows the id of a media item can currently stream it. This one is a bit tricky to fix, since we can't add authentication to the streams (problems with some players). Instead we should set some value when the player is loaded (where we do have authorization) and check that value when creating a stream.

**Comment by DieBagger** [comment]
if we would just create a random number and return it in the startstream method we wouldn't even need any changes (at least not for ampdroid)

**Comment by oxan** [comment]
I don't see any relation between this issue and StartStream and aMPdroid. The problem here is that in WebMP the /Stream/Movie?item=5 does all the work needed to setup a stream (InitStream, StartStream and redirects to RetrieveStream), while you don't need a password for it.
