### ISSUE TITLE
Download link in webMP

### ISSUE THREAD

**Issue by lyfesaver** [MPExtended/MPExtended#87]
I would like to request an option to be put in the the settings for each account to allow (or not allow) a link to download the selected video.

BTW, this is my first experience with GIT/GITHUB, so I hope I am doing this right. If I a wrong, I am sorry.

**Comment by oxan** [comment]
Hmm, this is actually more about per-user settings and permission control then about adding a download link (which I already added in c441311), isn't it? That's a good idea but it's quite a bit of a work. 

Oh, and don't worry, you're doing it right ;)

**Comment by lyfesaver** [comment]
I guess to have it set by user permissions is a bit much. It makes sense that if I let someone connect to my webMP that it wont matter to me if they download or stream. I am just glad you added it =)

**Comment by lyfesaver** [comment]
Looks like it works good within the limitations of issue #110.
