### ISSUE TITLE
Enable/disable WebMP from the configurator

### ISSUE THREAD

**Issue by oxan** [MPExtended/MPExtended#91]
(discussion drifted a bit offtopic below, it's mainly about enabling/disabling webmp from the configurator now. Original issue has been split out top #94). 

Use same user database for WebMP and the service.

**Comment by lyfesaver** [comment]
Could it be possible to have webMP just be a tick box inside MPEC to turn on and off. If you merge the same user database/source i would think it would not be too had to have MPEC to control webMP.

**Comment by oxan** [comment]
(assuming you mean the tray app with MPEC)

I don't really think that's possible to do soon. It might turn out to be a good idea in the long term, but I don't think it's a good idea to do now:
- We can't configure Windows services from the tray app due to UAC. This would require some fancy UacHelper interface.
- What about people who install WebMP on a computer without the service or configurator installed?
- What about people with a full IIS installation (they don't want IIS Express)

**Comment by lyfesaver** [comment]
Correct, I agree with all that.... and yes from the try icon would be nice, but in the config window itself was what I was originally referring to.

Please keep in mind, my ideas come from that of a user standpoint, not a dev. These are just ideas that as user I would think would be good. So i am sure to be chock full of errors =)

If you want webMP then fine, then a simple installer package. I would think that the installer could detect IIS7 or not and if it isn't then an extra window in the installer requests to add IISE.

But for those of us who DO install MPE (assuming the MPE installer always installs webMP too, and possibly ISSE if needed) and use the MPEC (main window) a settings option to turn on (or off) webMP. If turned on other options become available, like:

Allow download link (admins only)
Allow download link (all users)
etc...

... and if you wanted to get really crazy the same place could have options to restrict uplink speed per user and so on and so on. We have 4 MP users in the house so a user based system would be awesome, but certainly not needed. 

Hope I have explained what i mean clearly. And they are just ideas... some are bad ideas I am sure =)

**Comment by oxan** [comment]
(I think we are getting a bit offtopic here. I've split out the 'use same users for WebMP and service' featurerequest to #94, as I think we all agree on that)

First of all, as I'm mainly looking from the developer standpoint, I think I should clarify some technical restrictions:
- The tray application and the configuration window are actually the same program, so they run with the same permissions, which are user permissions. The best way to (technically) disable/enable WebMP is, in my opinion, to disable/enable the Windows service, which requires administrator permissions. It's a bit annoying to implement things like this but it's possible.
- The installer environment is fairly limited. I prefer to don't do too much fancy things in it, as it's very hard to implement properly. I think I'll be able to go as far as showing screens depending on whether IIS or IIS Express is installed, but automatically installation probably won't work. 
- There is still the problem of bundling IIS Express (#63), which I'm not sure I'll be able to resolve at all. I blame totally lacking documentation related to MSI chaining for this. 

That said, I think the idea itself is good, but it's a bit hard to implement now. 

As for the permission control, I think that was actually planned long ago but we didn't get to implementing it. I think it'll surely be added in the future, but not for 0.5 yet. Uplink speed limits probably won't come though, as we can't limit that in WCF (the services). We can workaround that in WebMP, but that'll cost quite some performance for people not using it.

Btw, I don't mind users posting lots of ideas. I'll just shoot down the impossible ones =)
